### ISSUE TITLE
Dead link to cluttr results

### ISSUE THREAD

**Issue by Madd0g** [microsoft/CodeT#12]
in DIVERSE/data/clutrr.md there's a link to 

https://dkibdm.blob.core.windows.net/llmpublic/clutrr_code_davinci_002.zip

and it's dead. 

Thanks!

**Comment by linzeqipku** [comment]
Hi @Madd0g , thanks for the notification!
We will update the link in this week and have you updated.

**Comment by linzeqipku** [comment]
Hi @Madd0g , the link has been fixed. Let me know if it works for you. Thanks :-)

**Comment by Madd0g** [comment]
Thank you very much for the quick resolution!
