### ISSUE TITLE
Missing pkl files

### ISSUE THREAD

**Issue by abuvaneswari** [microsoft/CodeT#15]
Hi,

When I execute:
python run_pipeline.py

I encounter the error:
FileNotFoundError: [Errno 2] No such file or directory: 'cache/vector/repos/repositories/huggingface_diffusers_ws20_slice2.one-gram.pkl'

In fact, there is no pkl file available under: cache/vector/repos/repositories/
Also, no pkl file is present under: cache/window/random_api/gt/repositories/

Please upload the missing pkl files. Or, supply instructions on the method to generate these pkl files.

Thank you

**Comment by HMJW** [comment]
Same question... The author had better fix the bugs in the code as soon as possible...

**Comment by pitikorn32** [comment]
face same issue...

**Comment by leonelmota** [comment]
Someone found a solution?

**Comment by zfj1998** [comment]
Thanks for your interest in our work. Sorry for the late. The cache files under "vector/repos/" are vectorized code fragments built from the code files within a repo. During code search, the vectorized code fragments are used for similarity comparison. So before running RG1 or repocoder method, we need to vectorize the code windows produced from each repo by calling the vectorize_repo_windows() function. I have updated the code in this commit (https://github.com/microsoft/CodeT/pull/20/commits/6a6ef6359a3587e134d8350c3eebb0e639e7789a). Sorry for the inconvenience again.
