### ISSUE TITLE
Missing code for inference

### ISSUE THREAD

**Issue by Lyz1213** [microsoft/CodeT#28]
Thanks for your wonderful work. 

However, there's no implementation of inference in the current run_pipeline.py. 

For the purpose of reproduction, could you kindly provide the script for inference based on the built prompt?

**Comment by JeremyJC67** [comment]
same question!

> Thanks for your wonderful work.
> 
> However, there's no implementation of inference in the current run_pipeline.py.
> 
> For the purpose of reproduction, could you kindly provide the script for inference based on the built prompt?

**Comment by leonelmota** [comment]
I have the same problem, did you find a solution?

**Comment by pppyb** [comment]
same question！

**Comment by zfj1998** [comment]
Thanks for your interest in our work! Sorry for the late, here is an update for the CodeGen inference script, as in commit (https://github.com/microsoft/CodeT/commit/cecce36b082e0e78c0c4097a7cb4777e5e7d5f28).
