### ISSUE TITLE
 No such file or directory: 'cache/window/random_api/gt/huggingface_diffusers_ws20.pkl

### ISSUE THREAD

**Issue by hgcdanniel** [microsoft/CodeT#29]
hi，when  I run run_pipeline.py ,No such file or directory: 'cache/window/random_api/gt/huggingface_diffusers_ws20.pkl

**Comment by leonelmota** [comment]
i`m running on the same problem, did you find a solution?

**Comment by zfj1998** [comment]
Can you provide more details on reproducing this issue? We notice that the code version in the main branch may lead to such an issue (https://github.com/microsoft/CodeT/issues/26). You may try to pull code from the zfj/RepoCoder branch to see if this problem is solved.

**Comment by pppyb** [comment]
I have the same question:
<img width="968" alt="image" src="https://github.com/microsoft/CodeT/assets/71714064/bda484d3-3f02-4453-8af3-5c13d59d18c2">

**Comment by zfj1998** [comment]
The reason of this issue can be found in https://github.com/microsoft/CodeT/pull/22, which has been fixed in zfj/RepoCoder branch
