### ISSUE TITLE
Inquiry About Retrieving and Generating Different Lengths of Datasets

### ISSUE THREAD

**Issue by pppyb** [microsoft/CodeT#41]
Hi,

Thank you for all the amazing work you've done on this project. It's been really helpful!

I am currently working on some experiments where I want to try datasets of different lengths. I noticed that the original dataset, such as the API-level dataset, is available in lengths like 1k, 2k, and 4k. I am curious about the process of how these datasets are retrieved or generated from the repository.

Could you please provide some insights or share the relevant code that details the retrieval or generation of these different lengths of datasets? This would be extremely helpful for my experiments.

Thank you very much for your assistance and for the excellent work you continue to do.

Best regards,
Brynn

**Comment by zfj1998** [comment]
The reason that we constructed prompts with "1k, 2k, and 4k" token lengths is to perform the ablation experiments on the length of the retrieved context. These "1k, 2k, or 4k" tokens do not include the retrieved context; they only include the prefix code of the target completion hole. 

If you are curious about how we choose the completion holes, For the random completion dataset, we just randomly pick the  non-repetitive code lines from the repository, ensuring the code line meets some conditions. For the API completion dataset,  we first run the ast parser over the whole repository, identify functions defined inside the repo. Then, we iterate over the code lines in the repository and identify the lines that called the previously identified APIs. I will clean my code and upload to my branch later.

**Comment by zfj1998** [comment]
https://github.com/microsoft/CodeT/commit/f7e8e6d729e358e4e3031521d7d96ea9bfecd524
scripts already uploaded, you can refer to the `api_benchmark.py` and `random_benchmark.py` for details of constructing these two datasets.
