### ISSUE TITLE
Releasing generated data for MBPP

### ISSUE THREAD

**Issue by Tiiiger** [microsoft/CodeT#5]
Hi All, 

Great work! 

I am wondering if you can also release the generated data for MBPP? Similar to the ones you released for HumanEval.

https://github.com/microsoft/CodeT/tree/main/CodeT/data/generated_data

Thank you!

**Comment by BellaBei** [comment]
Hi! Thanks for your interests in our work. We have released the generated data for MBPP, APPS and CodeContests. Please check out them in the repo!
