### ISSUE TITLE
Data split, prompt, and model predictions for CLUTRR

### ISSUE THREAD

**Issue by veronica320** [microsoft/CodeT#9]
Hi authors, thanks for the great work! Would it be possible to share more details about the CLUTRR dataset, e.g. the data split, the prompt you used, and the model predictions?

Thanks!

**Comment by linzeqipku** [comment]
Hi @veronica320 , I've just added this page https://github.com/microsoft/CodeT/blob/main/DIVERSE/data/clutrr.md

Let me know whether it works for you or not.
